### ISSUE TITLE
Angelo breaks with newer version of HTTP gem

### ISSUE THREAD

**Issue by kylekyle** [kenichi/angelo#62]
A fresh installation: 

```bash
$ rvm gemset empty
$ gem install http angelo
```

`angelo.rb`:

```ruby
require 'angelo'

class Server < Angelo::Base
  get '/' do
    "Hello world"
  end
end
```

```bash
$ ruby angelo.rb
I, [2016-03-12T16:54:45.041077 #84532]  INFO -- : Celluloid 0.17.3 is running in BACKPORTED mode. [ http://git.io/vJf3J ]
I, [2016-03-12T16:54:45.334780 #84532]  INFO -- : Angelo 0.4.1
I, [2016-03-12T16:54:45.334898 #84532]  INFO -- : listening on 127.0.0.1:4567
E, [2016-03-12T16:54:52.654852 #84532] ERROR -- : Actor crashed!
NameError: uninitialized constant HTTP::Response::SYMBOL_TO_STATUS_CODE
	/Users/kyle/.rvm/gems/ruby-2.2.3/gems/angelo-0.4.1/lib/angelo.rb:97:in `log'
	/Users/kyle/.rvm/gems/ruby-2.2.3/gems/angelo-0.4.1/lib/angelo/server.rb:68:in `route!'
	/Users/kyle/.rvm/gems/ruby-2.2.3/gems/angelo-0.4.1/lib/angelo/server.rb:51:in `dispatch!'
	/Users/kyle/.rvm/gems/ruby-2.2.3/gems/angelo-0.4.1/lib/angelo/server.rb:29:in `block in on_connection'
	/Users/kyle/.rvm/gems/ruby-2.2.3/gems/reel-0.6.0/lib/reel/connection.rb:73:in `each_request'
	/Users/kyle/.rvm/gems/ruby-2.2.3/gems/angelo-0.4.1/lib/angelo/server.rb:27:in `on_connection'
	/Users/kyle/.rvm/gems/ruby-2.2.3/gems/reel-0.6.0/lib/reel/server.rb:50:in `call'
	/Users/kyle/.rvm/gems/ruby-2.2.3/gems/reel-0.6.0/lib/reel/server.rb:50:in `handle_connection'
	/Users/kyle/.rvm/gems/ruby-2.2.3/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
	/Users/kyle/.rvm/gems/ruby-2.2.3/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
	/Users/kyle/.rvm/gems/ruby-2.2.3/gems/celluloid-0.17.3/lib/celluloid/call/async.rb:7:in `dispatch'
	/Users/kyle/.rvm/gems/ruby-2.2.3/gems/celluloid-0.17.3/lib/celluloid/cell.rb:50:in `block in dispatch'
	/Users/kyle/.rvm/gems/ruby-2.2.3/gems/celluloid-0.17.3/lib/celluloid/cell.rb:76:in `block in task'
	/Users/kyle/.rvm/gems/ruby-2.2.3/gems/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `block in task'
	/Users/kyle/.rvm/gems/ruby-2.2.3/gems/celluloid-0.17.3/lib/celluloid/task.rb:44:in `block in initialize'
	/Users/kyle/.rvm/gems/ruby-2.2.3/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in `block in create'
```

**Comment by kenichi** [comment]
this was fixed on the reel_0.6 branch, which is now merged to master and released in 0.5.0
